# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bitmap_filter.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bitmap_filter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x62itmap_filter.proto\x12\x12imagesearch.bitmap\"V\n\x12\x42\x61tchFilterRequest\x12\x15\n\rcandidate_pks\x18\x01 \x03(\x0c\x12\x14\n\x0cquery_bitmap\x18\x02 \x01(\x0c\x12\x13\n\x0bmax_results\x18\x03 \x01(\x05\"\x87\x01\n\x13\x42\x61tchFilterResponse\x12\x14\n\x0c\x66iltered_pks\x18\x01 \x03(\x0c\x12\x18\n\x10total_candidates\x18\x02 \x01(\x05\x12\x16\n\x0e\x66iltered_count\x18\x03 \x01(\x05\x12\x14\n\x0c\x66ilter_ratio\x18\x04 \x01(\x02\x12\x12\n\nlatency_us\x18\x05 \x01(\x03\"Q\n\x11PushUpdateRequest\x12\x10\n\x08image_pk\x18\x01 \x01(\x0c\x12\x14\n\x0c\x62itmap_delta\x18\x02 \x01(\x0c\x12\x14\n\x0cis_evergreen\x18\x03 \x01(\x08\"%\n\x12PushUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x14\n\x12HealthCheckRequest\"\xd4\x01\n\x13HealthCheckResponse\x12>\n\x06status\x18\x01 \x01(\x0e\x32..imagesearch.bitmap.HealthCheckResponse.Status\x12\x1a\n\x12rocksdb_size_bytes\x18\x02 \x01(\x03\x12\x17\n\x0flast_cdc_offset\x18\x03 \x01(\x03\x12\x12\n\ncdc_lag_ms\x18\x04 \x01(\x03\"4\n\x06Status\x12\x0b\n\x07SERVING\x10\x00\x12\x0f\n\x0bNOT_SERVING\x10\x01\x12\x0c\n\x08\x44\x45GRADED\x10\x02\x32\xb2\x02\n\x13\x42itmapFilterService\x12^\n\x0b\x42\x61tchFilter\x12&.imagesearch.bitmap.BatchFilterRequest\x1a\'.imagesearch.bitmap.BatchFilterResponse\x12[\n\nPushUpdate\x12%.imagesearch.bitmap.PushUpdateRequest\x1a&.imagesearch.bitmap.PushUpdateResponse\x12^\n\x0bHealthCheck\x12&.imagesearch.bitmap.HealthCheckRequest\x1a\'.imagesearch.bitmap.HealthCheckResponseB7\n\"com.szwego.imagesearch.bitmap.grpcB\x11\x42itmapFilterProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bitmap_filter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\"com.szwego.imagesearch.bitmap.grpcB\021BitmapFilterProto'
  _globals['_BATCHFILTERREQUEST']._serialized_start=43
  _globals['_BATCHFILTERREQUEST']._serialized_end=129
  _globals['_BATCHFILTERRESPONSE']._serialized_start=132
  _globals['_BATCHFILTERRESPONSE']._serialized_end=267
  _globals['_PUSHUPDATEREQUEST']._serialized_start=269
  _globals['_PUSHUPDATEREQUEST']._serialized_end=350
  _globals['_PUSHUPDATERESPONSE']._serialized_start=352
  _globals['_PUSHUPDATERESPONSE']._serialized_end=389
  _globals['_HEALTHCHECKREQUEST']._serialized_start=391
  _globals['_HEALTHCHECKREQUEST']._serialized_end=411
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=414
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=626
  _globals['_HEALTHCHECKRESPONSE_STATUS']._serialized_start=574
  _globals['_HEALTHCHECKRESPONSE_STATUS']._serialized_end=626
  _globals['_BITMAPFILTERSERVICE']._serialized_start=629
  _globals['_BITMAPFILTERSERVICE']._serialized_end=935
# @@protoc_insertion_point(module_scope)
