# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.infra.pb import bitmap_filter_pb2 as bitmap__filter__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in bitmap_filter_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BitmapFilterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BatchFilter = channel.unary_unary(
                '/imagesearch.bitmap.BitmapFilterService/BatchFilter',
                request_serializer=bitmap__filter__pb2.BatchFilterRequest.SerializeToString,
                response_deserializer=bitmap__filter__pb2.BatchFilterResponse.FromString,
                _registered_method=True)
        self.PushUpdate = channel.unary_unary(
                '/imagesearch.bitmap.BitmapFilterService/PushUpdate',
                request_serializer=bitmap__filter__pb2.PushUpdateRequest.SerializeToString,
                response_deserializer=bitmap__filter__pb2.PushUpdateResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/imagesearch.bitmap.BitmapFilterService/HealthCheck',
                request_serializer=bitmap__filter__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=bitmap__filter__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class BitmapFilterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BatchFilter(self, request, context):
        """批量过滤: 输入候选集 + 商家 Bitmap, 返回匹配结果
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushUpdate(self, request, context):
        """单图推送更新 (写入可见性加速)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BitmapFilterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BatchFilter': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchFilter,
                    request_deserializer=bitmap__filter__pb2.BatchFilterRequest.FromString,
                    response_serializer=bitmap__filter__pb2.BatchFilterResponse.SerializeToString,
            ),
            'PushUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.PushUpdate,
                    request_deserializer=bitmap__filter__pb2.PushUpdateRequest.FromString,
                    response_serializer=bitmap__filter__pb2.PushUpdateResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=bitmap__filter__pb2.HealthCheckRequest.FromString,
                    response_serializer=bitmap__filter__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'imagesearch.bitmap.BitmapFilterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('imagesearch.bitmap.BitmapFilterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BitmapFilterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BatchFilter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imagesearch.bitmap.BitmapFilterService/BatchFilter',
            bitmap__filter__pb2.BatchFilterRequest.SerializeToString,
            bitmap__filter__pb2.BatchFilterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imagesearch.bitmap.BitmapFilterService/PushUpdate',
            bitmap__filter__pb2.PushUpdateRequest.SerializeToString,
            bitmap__filter__pb2.PushUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imagesearch.bitmap.BitmapFilterService/HealthCheck',
            bitmap__filter__pb2.HealthCheckRequest.SerializeToString,
            bitmap__filter__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
